//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.08 at 03:04:39 PM MST 
//


package ethan.jaxb.ruleset;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="round_pairing" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}round_range"/>
 *                   &lt;element name="result_data" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="round_result" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element ref="{}bracket_org" minOccurs="0"/>
 *                   &lt;element ref="{}method" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="requires_result_history" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="judge_pairing" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}round_range"/>
 *                   &lt;element ref="{}method"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="application" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "roundPairing",
    "judgePairing"
})
@XmlRootElement(name = "ruleset")
public class Ruleset {

    @XmlElement(name = "round_pairing", required = true)
    protected List<RoundPairing> roundPairing;
    @XmlElement(name = "judge_pairing", required = true)
    protected List<JudgePairing> judgePairing;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "application", required = true)
    protected String application;

    /**
     * Gets the value of the roundPairing property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roundPairing property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoundPairing().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ruleset.RoundPairing }
     *
     *
     */
    public List<RoundPairing> getRoundPairing() {
        if (roundPairing == null) {
            roundPairing = new ArrayList<RoundPairing>();
        }
        return this.roundPairing;
    }

    /**
     * Gets the value of the judgePairing property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the judgePairing property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJudgePairing().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ruleset.JudgePairing }
     *
     *
     */
    public List<JudgePairing> getJudgePairing() {
        if (judgePairing == null) {
            judgePairing = new ArrayList<JudgePairing>();
        }
        return this.judgePairing;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the application property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getApplication() {
        return application;
    }

    /**
     * Sets the value of the application property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setApplication(String value) {
        this.application = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}round_range"/>
     *         &lt;element ref="{}method"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "roundRange",
        "method"
    })
    public static class JudgePairing {

        @XmlElement(name = "round_range", required = true)
        protected RoundRange roundRange;
        @XmlElement(required = true)
        protected Method method;

        /**
         * Gets the value of the roundRange property.
         *
         * @return
         *     possible object is
         *     {@link RoundRange }
         *
         */
        public RoundRange getRoundRange() {
            return roundRange;
        }

        /**
         * Sets the value of the roundRange property.
         *
         * @param value
         *     allowed object is
         *     {@link RoundRange }
         *
         */
        public void setRoundRange(RoundRange value) {
            this.roundRange = value;
        }

        /**
         * Gets the value of the method property.
         *
         * @return
         *     possible object is
         *     {@link Method }
         *
         */
        public Method getMethod() {
            return method;
        }

        /**
         * Sets the value of the method property.
         *
         * @param value
         *     allowed object is
         *     {@link Method }
         *
         */
        public void setMethod(Method value) {
            this.method = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}round_range"/>
     *         &lt;element name="result_data" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="round_result" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element ref="{}bracket_org" minOccurs="0"/>
     *         &lt;element ref="{}method" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *       &lt;attribute name="requires_result_history" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "roundRange",
        "resultData",
        "bracketOrg",
        "method"
    })
    public static class RoundPairing {

        @XmlElement(name = "round_range", required = true)
        protected RoundRange roundRange;
        @XmlElement(name = "result_data")
        protected Ruleset.RoundPairing.ResultData resultData;
        @XmlElement(name = "bracket_org")
        protected BracketOrg bracketOrg;
        @XmlElement(required = true)
        protected List<Method> method;
        @XmlAttribute(name = "requires_result_history", required = true)
        protected boolean requiresResultHistory;

        /**
         * Gets the value of the roundRange property.
         *
         * @return
         *     possible object is
         *     {@link RoundRange }
         *
         */
        public RoundRange getRoundRange() {
            return roundRange;
        }

        /**
         * Sets the value of the roundRange property.
         *
         * @param value
         *     allowed object is
         *     {@link RoundRange }
         *
         */
        public void setRoundRange(RoundRange value) {
            this.roundRange = value;
        }

        /**
         * Gets the value of the resultData property.
         *
         * @return
         *     possible object is
         *     {@link Ruleset.RoundPairing.ResultData }
         *
         */
        public Ruleset.RoundPairing.ResultData getResultData() {
            return resultData;
        }

        /**
         * Sets the value of the resultData property.
         *
         * @param value
         *     allowed object is
         *     {@link Ruleset.RoundPairing.ResultData }
         *
         */
        public void setResultData(Ruleset.RoundPairing.ResultData value) {
            this.resultData = value;
        }

        /**
         * Gets the value of the bracketOrg property.
         *
         * @return
         *     possible object is
         *     {@link BracketOrg }
         *
         */
        public BracketOrg getBracketOrg() {
            return bracketOrg;
        }

        /**
         * Sets the value of the bracketOrg property.
         *
         * @param value
         *     allowed object is
         *     {@link BracketOrg }
         *
         */
        public void setBracketOrg(BracketOrg value) {
            this.bracketOrg = value;
        }

        /**
         * Gets the value of the method property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the method property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMethod().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Method }
         *
         *
         */
        public List<Method> getMethod() {
            if (method == null) {
                method = new ArrayList<Method>();
            }
            return this.method;
        }

        /**
         * Gets the value of the requiresResultHistory property.
         *
         */
        public boolean isRequiresResultHistory() {
            return requiresResultHistory;
        }

        /**
         * Sets the value of the requiresResultHistory property.
         *
         */
        public void setRequiresResultHistory(boolean value) {
            this.requiresResultHistory = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="round_result" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "roundResult"
        })
        public static class ResultData {

            @XmlElement(name = "round_result", required = true)
            protected List<RoundResult> roundResult;

            /**
             * Gets the value of the roundResult property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the roundResult property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getRoundResult().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Ruleset.RoundPairing.ResultData.RoundResult }
             *
             *
             */
            public List<RoundResult> getRoundResult() {
                if (roundResult == null) {
                    roundResult = new ArrayList<RoundResult>();
                }
                return this.roundResult;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}integer" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class RoundResult {

                @XmlAttribute(name = "name")
                protected BigInteger name;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setName(BigInteger value) {
                    this.name = value;
                }

            }

        }

    }

}
